version: 1.4.4
release-notes:
v1.4.4: Checkbox cells only toggle when the box itself is clicked (#42).
v1.4.3: Linux platform support.
v1.4.1: Fixed issues when adding new frames to animations. Adding new frames are editable again.
v1.4.0: Added undo/redo feature. Added settings for all view options. Added individual buttons to import bg/ground and weapon (to no longer reset animation data).
