version: 1.8.4
release-notes:
v1.8.4: Per-tile AI-region detection overlay (#35).
v1.8.3: Linux platform support.
v1.8.1: Display battle names before importing. Show warning with too many mapsprites in battle. Fixed errors when creating new enemy entry.
v1.8.0: Added undo/redo feature. Added settings for all view options. Small fixes to enemy item and item flag fields.
