version: 1.9.5
release-notes:
v1.9.5: Fix roof-flag visuals (#61), map animation save (#59), mapsetup entity overlay (#36), unused block overlay (#45), smaller window (#46).
v1.9.4: Linux platform support.
v1.9.2: Fixes and info for map animation panel.
v1.9.1: Fixes to removing map flags. Showing map name before loading map.
v1.9.0: Added undo/redo feature. Added settings for all view options. Small bug fixes.
v1.8.4: Added the missing Step flag.
